// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertManyFromFilesToBase64Parallel(arg1, arg2) {
  return window['go']['services']['ConverterService']['ConvertManyFromFilesToBase64Parallel'](arg1, arg2);
}

export function ConvertManyToFolder(arg1, arg2, arg3) {
  return window['go']['services']['ConverterService']['ConvertManyToFolder'](arg1, arg2, arg3);
}

export function GetImagePreview(arg1) {
  return window['go']['services']['ConverterService']['GetImagePreview'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['ConverterService']['SetContext'](arg1);
}
