// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {images} from '../models';
import {context} from '../models';

export function ConvertManyFromFilesToBase64Parallel(arg1:Array<string>,arg2:images.Options):Promise<Array<string>>;

export function ConvertManyToFolder(arg1:Array<string>,arg2:string,arg3:images.Options):Promise<Array<string>>;

export function GetImagePreview(arg1:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
