// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1:Record<string, Array<string>>):Promise<Array<string>>;

export function Search(arg1:string):Promise<Record<string, Array<string>>>;
