// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['services']['DuplicateService']['Delete'](arg1);
}

export function Search(arg1) {
  return window['go']['services']['DuplicateService']['Search'](arg1);
}
