// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {files} from '../models';

export function Rename(arg1:Array<string>,arg2:files.OptionRename):Promise<void>;
