// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';
import {context} from '../models';

export function GetNow():Promise<system.SystemMinimalInfo>;

export function Start():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
