// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupTempFiles() {
  return window['go']['main']['App']['CleanupTempFiles']();
}

export function HandleDroppedFiles(arg1) {
  return window['go']['main']['App']['HandleDroppedFiles'](arg1);
}

export function SaveDroppedFiles(arg1) {
  return window['go']['main']['App']['SaveDroppedFiles'](arg1);
}

export function SelectImagePaths() {
  return window['go']['main']['App']['SelectImagePaths']();
}

export function SelectOutputFolder() {
  return window['go']['main']['App']['SelectOutputFolder']();
}
