// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {frontend} from '../models';

export function CleanupTempFiles():Promise<void>;

export function SaveDroppedFiles(arg1:Array<main.FileData>):Promise<Array<string>>;

export function SelectFiles(arg1:string,arg2:Array<frontend.FileFilter>,arg3:boolean):Promise<Array<string>>;

export function SelectFolder(arg1:string):Promise<string>;
