// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CleanupTempFiles():Promise<void>;

export function HandleDroppedFiles(arg1:Array<string>):Promise<Array<string>>;

export function SaveDroppedFiles(arg1:Array<main.FileData>):Promise<Array<string>>;

export function SelectImagePaths():Promise<Array<string>>;

export function SelectOutputFolder():Promise<string>;
